services:
  pipeline:
    container_name: nyc_taxi_pipeline
    image: nyc_taxi_pipeline

    build:
      context: .
      dockerfile: Dockerfile

    environment:
      DATA_URL: https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2026-01.parquet

    volumes:
      - ./data:/app/data
      - ./logs:/app/logs